server:
  port: 8080

spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#
#      routes:
#        - id: PRODUCT-SERVICE
#          uri: lb://product-service
#          predicates:
#            - Path=/api/product/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: serviceDown
#                fallbackuri: forward:/fallback
#
#        - id: ORDER-SERVICE
#          uri: lb://order-service
#          predicates:
#            - Path=/api/order/**
#          filters:
#            - AuthenticationFilter
#
#        - id: INVENTORY-SERVICE
#          uri: lb://inventory-service
#          predicates:
#            - Path=/api/inventory/**
#          filters:
#            - AuthenticationFilter
#
#        - id: AUTH-SERVICE
#          uri: lb://auth-service
#          predicates:
#            - Path=/api/auth/**

eureka:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka

## actuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

#Resilinece4j Properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
    instances:
      authServiceDown:
        baseConfig: default
      productServiceDown:
        baseConfig: default
      inventoryServiceDown:
        baseConfig: default
      orderServiceDown:
        baseConfig: default

#Resilience4J time-limiter Properties
  timelimiter:
    configs:
      default:
        timeout-duration: 5s
#Resilience4J Retry Properties
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s

