## PORT
server:
  port: 0
spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      database: store_db
      port: 27017
      uri: mongodb://localhost:27017/store_db

eureka:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka
  client:
    register-with-eureka: true
    fetch-registry: true